### ISSUE TITLE
Wrong data is getting returned from is_elixir_troop attribute

### ISSUE THREAD

**Issue by Anubhav1603** [mathsman5133/coc.py#101]
getting this list -> ['Barbarian', 'Archer', 'Goblin', 'Giant', 'Wall Breaker', 'Balloon', 'Wizard', 'Healer', 'Dragon', 'P.E.K.K.A', 'Baby Dragon', 'Miner', 'Yeti', 'Sneaky Goblin', 'Electro Dragon', 'Dragon Rider']

Error -> Sneaky Goblin is not elixir troop but its included

How to reproduce error
```py
import coc
from coc import utils
fixed_tag = utils.correct_tag(player_tag) 
player = await self.bot.coc.get_player(fixed_tag)
print([f"{t.name}" for t in player.troops if t.is_elixir_troop ])
```

**Comment by masonhorne** [comment]
While investigating this in #107 I realized Sneaky Goblins are in fact an elixer troop in game.
