### ISSUE TITLE
discordlinks api not working

### ISSUE THREAD

**Issue by virusv2** [mathsman5133/coc.py#103]
When calling this function: 

> async def player_link(player_tag: str) -> str:
    link_id = await link_client.get_link(player_tag)
    if link_id == "":
        link_str = 'Player tag is not linked.'
    else:
        link_str = 'Player is linked to <@{}>.'.format(
            link_id)
    return link_str

Here is how the link_client:
>link_client = discordlinks.login(
    username=os.getenv("link_user"),
    password=os.getenv("link_pass"))

I get the attached traceback error: [message (1).txt](https://github.com/mathsman5133/coc.py/files/8545798/message.1.txt)

**Comment by majordoobie** [comment]
Would like to add that failing to authenticate causes an infinite recursion to occur when attempting to fetch the keys needed to talk to the API. 

Suggestion should be that the login should return a None or something indicating that authentication failed.

**Comment by virusv2** [comment]
I was able to resolve this issue after I reinstalled coc.py. :)
