### ISSUE TITLE
module 'coc' has no attribute 'login'

### ISSUE THREAD

**Issue by TheDarkLach** [mathsman5133/coc.py#104]
Title, I am not sure why it is saying coc does not have the attribute login.

**Comment by wpmjones** [comment]
This often happens when you have your own file named coc.py. Please make sure your project doesn't have a file with they name.

**Comment by lukasthaler** [comment]
This also happens if you `pip install coc` instead of `pip install coc.py`. Make sure you are installing the correct library

**Comment by TheDarkLach** [comment]
Thanks I think the problem was missing the .py :D
