### ISSUE TITLE
How do you retrieve War Attacks

### ISSUE THREAD

**Issue by drink-and-derive** [mathsman5133/coc.py#110]
I'm going through the War Logs in an attempt to get the War attacks of members of our clans however from the documentation this does not populate war.clan.attacks or war.clan.members properties. I was wondering if there is an alternative way to get the ClanWar object for non-CWL attacks besides going through the War Logs. I've been searching through the documentation, but I'm not seeing anything to get this information.

**Comment by doluk** [comment]
sadly this is a mistake in the API documentation.  The warlog endpoint returns no data about the attacks of a member.

The only way to get those is to use the current war, in this wrapper: `await client.get_current_war()`.
