### ISSUE TITLE
Loop cleanup

### ISSUE THREAD

**Issue by majordoobie** [mathsman5133/coc.py#111]
With the new async wrapper introduced in 3.8, the wrapper cleans up the loop after the loop is done. This causes an issue when running `coc_client.close()` since it 

1) Is called synchronously (not really an issue)
2) Closes the main loop

Example:
```py
from pathlib import Path

import coc
import asyncio
from packages.private.settings import Settings


async def main():
    settings = Settings(Path("."), "live_mode")
    coc_client = coc.Client()
    await coc_client.login(settings.coc_user, settings.coc_pass)

    clan = await coc_client.get_clan('#2L9JVLPLG')
    async for player in clan.get_detailed_members():
        print(player.name)
        
    # This breaks
    coc_client.close()
    
    # New implementation seems to work
    await coc_client.client_close()

if __name__ == '__main__':

    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
```

I already have a fork. Going to add the code and make an example.

**Comment by skouv05** [comment]
I get an AttributeError: 'Client' object has no attribute 'client_close' when trying that

**Comment by majordoobie** [comment]
This is an `issue`. Once I implement the code I will submit it as a pull request. Then it is up to the owner to either accept it or not. It will not be available to you until it is merged and released.
