### ISSUE TITLE
PlayerEvents.clan_rank() not firing

### ISSUE THREAD

**Issue by bobflem** [mathsman5133/coc.py#118]
Example:
```
import coc
import os
import logging

client = coc.login(os.environ['COCAPI_EMAIL'], os.environ['COCAPI_PASSWORD'], client=coc.EventsClient)
logging.basicConfig(level=logging.INFO)
log = logging.getLogger()

clan_tag = [os.environ['CLASH_CLANTAG']]

@coc.PlayerEvents.clan_rank()
async def on_player_rank_change(old_player, new_player):
    log.info(f"{new_player} moved from #{old_player.clan_rank} to #{new_player.clan_rank}.")

async def main(): #add clan members to player updates
    async for clan in client.get_clans(clan_tag):
        client.add_player_updates(*[member.tag for member in clan.members])
    client.add_events(on_player_rank_change)

try:
    client.loop.run_until_complete(main())
    client.loop.run_forever()
except KeyboardInterrupt:
    pass
```
The event registers, but doesn't seem to fire when a leaderboard change occurs.

> INFO:coc.events:Successfully registered <function on_player_rank_change at 0x7f497f3c4790> event

Am I doing something wrong?

**Comment by doluk** [comment]
what coc.py version are you using? 
With the latest version the creation of the client has changed. So I assume it isn't the latest

**Comment by majordoobie** [comment]
Not sure that will work since you already have the event loop running until complete with the `coc.login`. 

Try logging in with the class instead. 
https://github.com/mathsman5133/coc.py/blob/master/examples/events_example.py

**Comment by bobflem** [comment]
That might work, but that wouldn't explain why the same code works for trophy changes (obviously using the correct event).

So if I use the trophies event instead of the clan_rank event:
```
@coc.PlayerEvents.trophies()
async def on_player_trophy_change(old_player, new_player):
    log.info(f"{new_player} trophies changed from {old_player.trophies} to {new_player.trophies}")
```
It works just fine. I will try what you suggested a little later, but I don't think it will make a difference if another player event is firing just fine.

**Comment by majordoobie** [comment]
If your other events are firing, then yeah you are right. What I provided will not make a difference. I will look after work today to see what the problem is.

**Comment by Bla005-1** [comment]
clan_rank is an attribute of ClanMember and the event needs to be an attribute of Player. This is important because ClanMember comes from a different endpoint of the api I believe.

**Comment by bobflem** [comment]
> clan_rank is an attribute of ClanMember and the event needs to be an attribute of Player. This is important because ClanMember comes from a different endpoint of the api I believe.

You got it! What I needed to use was ClanEvents.member_clan_rank().
