### ISSUE TITLE
"Microsoft Visual C++ 14.0 is required" but already installed

### ISSUE THREAD

**Issue by TucTitan** [mathsman5133/coc.py#13]
While installing the coc.py with `py -3 -m pip install -U coc.py` i got following issue:

`ERROR: Complete output from command 'C:\Users\******\AppData\Local\Programs\Python\Python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\*******\\AppData\\Local\\Temp\\pip-install-6yl2cf14\\lru-dict\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\********\AppData\Local\Temp\pip-record-8gehi4fb\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_ext
    building 'lru' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/`

but Microsoft Visual C++ 14.0 is installed

**Comment by wpmjones** [comment]
I had the same problem.  They want the build tools installed.  Go to https://visualstudio.microsoft.com/downloads/, scroll down to the section that says All Downloads, expand the section for Tools for Visual Studio 2019, and download/install Build Tools for Visual Studio 2019.

**Comment by TucTitan** [comment]
Already did this... But dont know what i have to do in this Buildtool

**Comment by wpmjones** [comment]
You don't need to do anything with the Build Tools.  Just install them.  It says Visual C++ 14.0 but that's really not what it's looking for.  It's very specifically looking for those build tools to be installed on your system.  After I installed the Build Tools and rebooted, coc.py worked perfectly.

**Comment by TucTitan** [comment]
I would appreciate it, but still have the same error after reboot :(
The programm I have to install is named `Visual Studio Installer` after installation right?

**Comment by wpmjones** [comment]
No, I gave you direct instructions above.  It's Build Tools for Visual Studio 2019.  Here is a direct link to the download - https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16

**Comment by TucTitan** [comment]
Sorry, but still get the same error :(

I installed the Build Tools now correctly... Didn't do it on the first time but now i see it in my Apps.
But I still get the same error :(

**Comment by mathsman5133** [comment]
Hi there, after some digging, I would like to see if either of these 2 fix the problem:

First:
`pip install setuptools --upgrade`
`pip install coc.py --upgrade`

If that doesn't work:
`pip install --only-binary :all: coc.py`

**Comment by TucTitan** [comment]
No, it doesn't work...

The `pip install setuptools --upgrade` pushed the version from 40.8.0 to 41.0.1 but the rest fails:

**********************************************************************************
Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

`PS C:\DATEN\Programmieren\COC Bot> py -3 -m pip install setuptools --upgrade`
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
     |████████████████████████████████| 583kB 1.6MB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 40.8.0
    Uninstalling setuptools-40.8.0:
      Successfully uninstalled setuptools-40.8.0
Successfully installed setuptools-41.0.1
`PS C:\DATEN\Programmieren\COC Bot> py -3 -m pip install coc.py --upgrade`
Collecting coc.py
  Using cached https://files.pythonhosted.org/packages/67/48/fbe2316074a0cfe3dfc578c677556e4ef9b81cea0e27a243bc9b3a348e95/coc.py-0.1.2-py3-none-any.whl
Collecting lru-dict (from coc.py)
  Using cached https://files.pythonhosted.org/packages/00/a5/32ed6e10246cd341ca8cc205acea5d208e4053f48a4dced2b1b31d45ba3f/lru-dict-1.1.6.tar.gz
Requirement already satisfied, skipping upgrade: aiohttp<3.6.0,>=3.3.0 in c:\users\******\appdata\local\programs\python\python37-32\lib\site-packages (from coc.py) (3.5.4)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in c:\users\******\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.6.0,>=3.3.0->coc.py) (3.0.4)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in c:\users\******\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.6.0,>=3.3.0->coc.py) (19.1.0)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.6.0,>=3.3.0->coc.py) (3.0.1)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.6.0,>=3.3.0->coc.py) (1.3.0)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.0 in c:\users\*********\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp<3.6.0,>=3.3.0->coc.py) (4.5.2)
Requirement already satisfied, skipping upgrade: idna>=2.0 in c:\users\*******\appdata\local\programs\python\python37-32\lib\site-packages (from yarl<2.0,>=1.0->aiohttp<3.6.0,>=3.3.0->coc.py) (2.8)
Installing collected packages: lru-dict, coc.py
  Running setup.py install for lru-dict ... error
    ERROR: Complete output from command 'C:\Users\******\AppData\Local\Programs\Python\Python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\******\\AppData\\Local\\Temp\\pip-install-u1az08k3\\lru-dict\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\*******\AppData\Local\Temp\pip-record-97sg2czx\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_ext
    building 'lru' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command "'C:\Users\*******\AppData\Local\Programs\Python\Python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\tomni\\AppData\\Local\\Temp\\pip-install-u1az08k3\\lru-dict\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\******\AppData\Local\Temp\pip-record-97sg2czx\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\******\AppData\Local\Temp\pip-install-u1az08k3\lru-dict\
`PS C:\DATEN\Programmieren\COC Bot> py -3 -m pip install --only-binary :all: coc.py`
Collecting coc.py
  Using cached https://files.pythonhosted.org/packages/67/48/fbe2316074a0cfe3dfc578c677556e4ef9b81cea0e27a243bc9b3a348e95/coc.py-0.1.2-py3-none-any.whl
Collecting lru-dict (from coc.py)
  ERROR: Could not find a version that satisfies the requirement lru-dict (from coc.py) (from versions: none)
ERROR: No matching distribution found for lru-dict (from coc.py)
`PS C:\DATEN\Programmieren\COC Bot>`
**************************************************************************************

**Comment by mathsman5133** [comment]
I am currently working on a fix which will make `lru-dict` requirement redundant, thus nullifying this issue. Will be fixed ASAP. Thanks for the issue!

**Comment by mathsman5133** [comment]
If you do `pip install -U coc.py --upgrade`, I have pushed a major update you can read about [here](https://cocpy.readthedocs.io/en/latest/changelog.html) 😄

**Comment by TucTitan** [comment]
Good job!

It ends with `Successfully installed coc.py-0.1.3`

Thank you very much!!!
