### ISSUE TITLE
Add Support for CapitalRaidSeasons

### ISSUE THREAD

**Issue by SplatTab** [mathsman5133/coc.py#131]
[/clans/{clanTag}/capitalraidseasons](https://developer.clashofclans.com/api-docs/index.html#/clans/getCapitalRaidSeasons)

You can now retrieve capital raid seasons from the coc api. So add support for this in clans.

Thanks add soon because this is very epic thanks supercell.

**Comment by majordoobie** [comment]
v2.2.0 has been released
