### ISSUE TITLE
Incorrect Minimum Level being returned on Siege Machines

### ISSUE THREAD

**Issue by btimothy-har** [mathsman5133/coc.py#143]
```
troop = coc_client.get_troop(name="Siege Barracks",townhall=12)
m = troop.get_max_level_for_townhall(12)
```
returns m == 3, which is incorrect as Siege Barracks is not available at TH12.

Same issue persists for the following sieges at TH12:
- Log Launcher returns 3
- Flame Flinger returns 3

And at TH11:
- Battle Blimp returns 1
- Wall Wrecker returns 1
- Stone Slammer returns 1

**Comment by majordoobie** [comment]
Doesn't TH12 have siege barracks? I am working gon a unit test to make sure our changes work but looking it up it looks like we have it right? Am I reading this incorrectly? https://clashofclans.fandom.com/wiki/Siege_Barracks

**Comment by majordoobie** [comment]
Ah sorry I was looking at the wrong link. Thanks! I'll write the unit test then merge the PR for it.
