### ISSUE TITLE
Hero pets have undesirable ID values.

### ISSUE THREAD

**Issue by zengfung** [mathsman5133/coc.py#156]
All hero pets currently have ID = 0. This results in bugs when trying to run similar workflow on hero pets with heroes, troops, and spells, all of which have distinct IDs.

Also, `client.get_pet('<petname>, level=1)` does not work, whereas `client.get_pet('<petname>')` and `client.get_pet('<petname>', townhall=14)` works as expected.

**Comment by doluk** [comment]
looks like the source of the static files we use doesn't contain any sort of ids. I added a fallback id to ensure the id is not 0 with the latest commit to the branch for the next version
