### ISSUE TITLE
Things to keep in mind for v3

### ISSUE THREAD

**Issue by Kuchenmampfer** [mathsman5133/coc.py#170]
- rename `WarLeague` to `ClanLeague`
- remove `coc.login()` and `coc.login_with_keys()`
- rename `get_warlog` to `get_war_log` and `get_raidlog` to `get_raid_log`

**Comment by mathsman5133** [comment]
I'd also like to clean up any old asyncio stuff & have a good think about the best way of doing anything async-related, and think about declaring events and whether that is good / bad / ugly / an easier way that is perhaps typehinted or something

**Comment by doluk** [comment]
the `BatchThrottler` seems kinda broken or is very slow

**Comment by serpentinesr** [comment]
is `coc.login()` going to be removed?

**Comment by doluk** [comment]
Yes it is marked as depreciated
