### ISSUE TITLE
Hero.required_th_level False Documentation

### ISSUE THREAD

**Issue by MasterNoob34** [mathsman5133/coc.py#197]
The output is documented as `int` but it actually returns `UnitStatList`.

Code
```py
hero = client.get_hero(hero_name)
if hero.required_th_level <= min_townhall:
   # do something
```
<img width="410" alt="Screen Shot 2023-05-18 at 13 07 22" src="https://github.com/mathsman5133/coc.py/assets/133764760/3c834c22-46f9-4062-a589-49aa29f136bf">

Error
```
TypeError: '<=' not supported between instances of 'UnitStatList' and 'int'
```

**Comment by doluk** [comment]
Can you post your code snippet here please?

**Comment by MasterNoob34** [comment]
> Can you post your code snippet here please?

Sorry, posted them now!

**Comment by doluk** [comment]
yeah, you just got the hero without a level. You need to get the hero for a level, then the return value should be an int

**Comment by MasterNoob34** [comment]
Ok thank you, didn't know. I thought it was return int.
