### ISSUE TITLE
Impossible to catch PrivateWarLog

### ISSUE THREAD

**Issue by Anatras** [mathsman5133/coc.py#20]
I don't if I don't know how to catch it, but it does not work with except coc.errors.PrivateWarLog:

**Comment by mathsman5133** [comment]
```
try:
    await coc.get_current_war('clantag')
except coc.PrivateWarLog:
    pass
```
Should work now. Thanks for the issue!

**Comment by mathsman5133** [comment]
If you have discord and would be interested in joining the clash API discord server, the invite is [here](https://discord.gg/GTTFsVA)... there is a designated channel for coc.py and a lot of very helpful friendly people 😄
