### ISSUE TITLE
Super Hog Rider and Apprentice Warden additions

### ISSUE THREAD

**Issue by Westo48** [mathsman5133/coc.py#202]

**Comment by GILLESMaster** [comment]
^

**Comment by GustavoSchip** [comment]
The Battle Copter needs to be added as well!
@Westo48 Or is this added already?
Because for me the returned hero's don't include the battle copter?
And as a bonus action the calculation with troop levels with town halls is broken:

```python
troops = {}
        for troop in player.home_troops:
            if not troop.is_super_troop:
                troops[troop.name] = {
                    "name": troop.name,
                    "player": troop.level,
                    "max for the th": troop.get_max_level_for_townhall(player.town_hall),
                    "max for the game": troop.max_level,
                }
```

Errors with:

```python
  File "/home/gustavo/PycharmProjects/Clashy-Besi/venv/lib/python3.11/site-packages/coc/troop.py", line 155, in get_max_level_for_townhall
    for lab_level, th_level in cls.lab_to_townhall.items():
                               ^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Troop' has no attribute 'lab_to_townhall'
```

**Comment by MagicTheDev** [comment]
It's been fixed and added in https://github.com/mathsman5133/coc.py/tree/g10_3.0.0 . I guess we're just waiting for a few things for v3

**Comment by GustavoSchip** [comment]
> It's been fixed and added in https://github.com/mathsman5133/coc.py/tree/g10_3.0.0 . I guess we're just waiting for a few things for v3

So do I just install the developer version, or that specific branch?

**Comment by doluk** [comment]
That specific branch is the development version currently @GustavoSchip

**Comment by Westo48** [comment]
Closing with 3.0.0
