### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by GustavoSchip** [mathsman5133/coc.py#207]
```python
ERROR:root:Events had an error!
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/coc/events.py", line 1067, in _run_war_update
    war = await meth(clan_tag, cls=self.war_cls, round=cwl_round)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/coc/client.py", line 1143, in get_current_war
    async for war in self.get_league_wars(league_group.rounds[-1], cls=cls, **kwargs):
                                          ~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```

this is what occurs if you have a clan_tag that is in league and a clan_tag that isnt in the league,
is there any way to get around this?

functions used:

```python
@coc.WarEvents.war_attack(tags=clan_tags)
    async def _current_war_stats(attack, war):
        log.info("Event triggered")
        clan_tag = war.clan.tag
        embed = create_embed(
            f"{escape_markdown(war.clan.name)}: War attack",
            f"Attack number {attack.order}\n({attack.attacker.map_position}). `{escape_markdown(attack.attacker.name)}` of {escape_markdown(attack.attacker.clan.name)} attacked ({attack.defender.map_position}). `{escape_markdown(attack.defender.name)}` of {escape_markdown(attack.defender.clan.name)}",
            discord.Colour.green(),
            "",
            "",
        )

        await send_embed_to_webhook(clan_tag, embed)

    @coc.WarEvents.new_war(tags=clan_tags)
    async def _new_war(war):
        log.info("Event triggered")
        clan_tag = war.clan.tag
        embed = create_embed(
            f"{escape_markdown(war.clan.name)}: War",
            f"New war against {escape_markdown(war.opponent.name)} initiated",
            discord.Colour.green(),
            "",
            "",
        )

        await send_embed_to_webhook(clan_tag, embed)
```

coc.py==2.4.1

**Comment by doluk** [comment]
@MagicTheDev is that the same one you had?

**Comment by MagicTheDev** [comment]
idk, i havent looked at events, my problem was/is with it fetching the first day. But probably related

**Comment by GustavoSchip** [comment]
@doluk @MagicTheDev sorry for my late reaction, vacation and stuff.

I have ignored this issue and removed it from my shell as it gets annoying but the actual event still works, so I don't know how that is supposed to work but it does, so silenced this output, and all is well I guess, but this is still weird to begin with and a big red flag for that matter.

Is there a clear way to fix this to begin with?

**Comment by GustavoSchip** [comment]
But this is still confusing,

have a tag without CWL and one that is in CWL and this is what you get if you listen to/for (I don't know English :joy:) both tags.

**Comment by doluk** [comment]
@GustavoSchip can you please send me those two tags?
I think I know what is causing this

**Comment by GustavoSchip** [comment]
> @GustavoSchip can you please send me those two tags? I think I know what is causing this

@doluk sure!

tag1 (in cwl):
`#2QJ8Q09J8`

tag2 (not cwl):
`#2Q0U0UL0R`

**Comment by GustavoSchip** [comment]
> > @GustavoSchip can you please send me those two tags? I think I know what is causing this
> 
> @doluk sure!
> 
> tag1 (in cwl): `#2QJ8Q09J8`
> 
> tag2 (not cwl): `#2Q0U0UL0R`

I believe these were the 2 I used

**Comment by doluk** [comment]
Cant reproduce it. On which date did this occur? Are you sure those are the correct tags?

**Comment by doluk** [comment]
Are you using the current version on pypi or the github.com repo to install coc.py? If it is pypi, I know what happend and the bug is already fixed!

**Comment by GustavoSchip** [comment]
> Are you using the current version on pypi or the github.com repo to install coc.py? If it is pypi, I know what happend and the bug is already fixed!

the version was in the issue, but its the latest pypi, as I cant seem to migrate my codebase

**Comment by GustavoSchip** [comment]
> Cant reproduce it. On which date did this occur? Are you sure those are the correct tags?

1 - 2 days ago

**Comment by doluk** [comment]
Okay I am sure I found the bug. It was indeed the already fixed caching one. I would suggest you to use the 3.0 branch, which fixes that. It will be released very soon

**Comment by GustavoSchip** [comment]
> Okay I am sure I found the bug. It was indeed the already fixed caching one. I would suggest you to use the 3.0 branch, which fixes that. It will be released very soon

Ah ok, but is the migration going to be hard?
Because with the beta branch without documentation I became stuck at some stupid problems

**Comment by doluk** [comment]
No, the important changes are:
 - renaming versus to builder_base
- renaming warlog and raidlog to war_log and raid_log
- the login shortcuts coc.login and coc.login_with_keys got removed

**Comment by GustavoSchip** [comment]
> No, the important changes are:
>  - renaming versus to builder_base
> - renaming warlog and raidlog to war_log and raid_log
> - the login shortcuts coc.login and coc.login_with_keys got removed

Ah ok, what is the recommended login method?
Il look into upgrading my codebase!

**Comment by GustavoSchip** [comment]
Il close this issue if I have it al covered!

**Comment by GustavoSchip** [comment]
@doluk 

I have managed to update!
Thanks for this great resource!
