### ISSUE TITLE
Raising this error when the clan is not in war

### ISSUE THREAD

**Issue by Anatras** [mathsman5133/coc.py#21]
'NoneType' object has no attribute 'time'
Traceback (most recent call last):
  File "/root/LootPvp/env/lib/python3.7/site-packages/pyrogram/client/ext/dispatcher.py", line 183, in update_worker
    await handler.callback(self.client, *args)
  File "/root/CoC/plugin/clan.py", line 52, in clan
    tipo = trad[clanWar.type]
  File "/root/LootPvp/env/lib/python3.7/site-packages/coc/wars.py", line 157, in type
    if (self.start_time.time - self.preparation_start_time.time).seconds == 82800:  # 23hr prep
AttributeError: 'NoneType' object has no attribute 'time'
@

**Comment by Anatras** [comment]
It would be cool to have an error "NotWar" that you can except

**Comment by mathsman5133** [comment]
What is the relevant code?

**Comment by Anatras** [comment]
```
                   tipo = trad[clanWar.type]
                    clanA = clanWar.clan
                    opponent = clanWar.opponent
                    numero = len(clanWar.members)
                    status = trad[clanWar.status]
```

This when the clan is not in war, I've fixed it by using excpet AttributeError, but I would be cool to have an error

**Comment by Anatras** [comment]
trad is just a dict to translate

**Comment by mathsman5133** [comment]
Thanks. `ClanWar.type` will now return `None` if the clan is not in war.

**Comment by Anatras** [comment]
Will the others (like clanWar.clan etc.) also return None?

**Comment by mathsman5133** [comment]
I'll add some notes in docs, but iirc team size, status, opponent, end_time, preparation_start_time, start_time, attacks (empty list), and members (empty list) all return `None`. `state` will return `notInWar`.
