### ISSUE TITLE
Spirit Fox being triggered as a troop

### ISSUE THREAD

**Issue by Vondyy** [mathsman5133/coc.py#217]
Whenever you're using the player event troop_change, whenever a user upgrade the "Spirit Fox", for some reason the troop_change get triggered.

    @coc.PlayerEvents.troop_change()
    async def on_player_troop_upgrade(self, old_player, new_player, troop):
        print(f"Processing troop upgrade for {new_player.name} {new_player.tag}")

**Comment by lukasthaler** [comment]
What version are you on? The latest release doesn't have the th16 content yet, the PR is still under review

**Comment by Vondyy** [comment]
we've discussed this on discord and the th16 branch still haven't been merged yet.
