### ISSUE TITLE
AttributeError: module 'coc' has no attribute 'login'

### ISSUE THREAD

**Issue by The-Arx** [mathsman5133/coc.py#234]
I just installed via pip and it says login isn't defined.

Example in the python console:
```
>>> import coc
>>> coc.__version__
'3.4.2'
>>> coc.login
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'coc' has no attribute 'login'
```

It doesn't seem to be imported in `__init__.py`.

**Comment by majordoobie** [comment]
That function has been deprecated. It is now `coc.Client.login`

see the examples: https://github.com/mathsman5133/coc.py?tab=readme-ov-file#quick-example

join the discord for questions like these, please. 

https://discord.gg/clashapi

**Comment by The-Arx** [comment]
Sorry I was using outdated documentation (https://cocpy.readthedocs.io/en/rewrite/api.html) which comes up when googling clash of clans API. It should probably be marked as outdated.
