### ISSUE TITLE
War & CWL end events

### ISSUE THREAD

**Issue by CancianMatteo** [mathsman5133/coc.py#241]
Is there a way to fetch data of the last war/CWL implemented in this library?
I was searching for an event trigger that when a war or CWL is ended fetch all the data about players attacks and stars at once.

**Comment by CancianMatteo** [comment]
Maybe in events.py after the "new_war" method you should add a "war_end" method?
`@classmethod
def war_ends(cls, tags=None, custom_class=None, retry_interval=None):
    """Alias for the war end time changes, indicating the war has ended"""

    async def wrapped(cached_war: ClanWar, war: ClanWar, callback):
        if cached_war.end_time and war.end_time \
                and cached_war.end_time.time != war.end_time.time:
            await callback(war)
        elif war.end_time and not cached_war.end_time:
            # no war on endpoint previously, so this end time indicates a war has just ended
            await callback(war)
    return _ValidateEvent.shortcut_register(wrapped, tags, custom_class, retry_interval, WarEvents.event_type)`

**Comment by MagicTheDev** [comment]
There is a war state event, could store when it is war ended?

**Comment by doluk** [comment]
Sure we can add this. Feel free to make a pull request :D

**Comment by CancianMatteo** [comment]
> There is a war state event, could store when it is war ended?

Could you please explain yourself better?

**Comment by doluk** [comment]
just use the war event and check on invoke if the new_war.state is equal to "warEnded"
