### ISSUE TITLE
Possible to get auth token & search clan via name?

### ISSUE THREAD

**Issue by xMistt** [mathsman5133/coc.py#26]
Is it possible to search a clan for the clan name as it's on the API but looking through the documentation I can't find it, if it isn't possible, is there anyway to get the auth key currently being used, something like ``coc.token`` so you can create custom requests easily?

**Comment by mathsman5133** [comment]
https://cocpy.readthedocs.io/en/latest/api.html#coc.Client.search_clans

ie. 
```py
client = coc.login('email', 'pass')
clans = await client.search_clans(name='clan name to search', limit=10)
```

The entirety of the API should be supported, however, you can check `coc.http` module to see how I handle keys and how to find the current key. If there are parts of the API you believe are unsupported please let me know and I'll fix it up.
