### ISSUE TITLE
Rewrite: Best Opponent Attack error

### ISSUE THREAD

**Issue by wpmjones** [mathsman5133/coc.py#51]
When asking for `member.best_opponent_attack`, if there were no attacks on the specified base, you get a TypeError because the function on line 90 of war_members.py (get_attack) expects two arguments (attacker_tag, defender_tag) but only gets one.  In this case, the function should either return `None` indicating that there were no attacks on that base.

Test case (probably only good for 2 more hours since a new war will start):
Clan: #CVCJR89
Player:  SMELLY COW (#GGJV88GG)

```
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python36\lib\site-packages\coc\war_members.py", line 90, in best_opponent_attack
    return self.war.get_attack((self._best_opponent_attacker, self.tag))
2020-07-14 16:38:21.331 | ERROR    | __main__:on_command_error:125 - TypeError: get_attack() missing 1 required positional argument: 'defender_tag'
```

**Comment by mathsman5133** [comment]
Should be fixed by https://github.com/mathsman5133/coc.py/commit/205e842324688cb787f5c2f97cf79e0418d2a72b. Thanks!

**Comment by wpmjones** [comment]
Fix confirmed!
