### ISSUE TITLE
ClanMember obj dont have town_hall attribute

### ISSUE THREAD

**Issue by Anubhav1603** [mathsman5133/coc.py#58]
```traceback
print(f"{member.name} townhall{member.town_hall} has joined {clan.name}")
AttributeError: 'ClanMember' object has no attribute 'town_hall'
```
i am using member_join event and it takes `clan` and `ClanMember` as param and i wnt to show town_hall also when member join how can i access that, as clanMember dont have this attribute

**Comment by mathsman5133** [comment]
You need to get the full player object with `player = await client.get_player(member.tag)` as the API doesn't give TH level for Clan Members in the clan endpoint.
