### ISSUE TITLE
ClientEvent maintenance error

### ISSUE THREAD

**Issue by Anubhav1603** [mathsman5133/coc.py#60]
![lint_error](https://user-images.githubusercontent.com/57266248/90957599-25ecb880-e4ac-11ea-9577-3d3babcece8d.PNG)
![maintain](https://user-images.githubusercontent.com/57266248/90957600-27b67c00-e4ac-11ea-96f9-a0c3074e1549.PNG)
Dont know y its failing

**Comment by mathsman5133** [comment]
This isn't anything to do with maintenance events, rather an update to pylint that means some of my code fails where it didn't before. I'm not bothered anymore since there is no more automatic linting.
