### ISSUE TITLE
Problem with aiohttp

### ISSUE THREAD

**Issue by abdurahmangulamkadirov** [mathsman5133/coc.py#66]
Hi there!
I've installed the library. But I've got a problem with this code:
```
import coc
coc.login(email, password, key_names, key_count)
```
The issue is:

Exception ignored in: <function ClientSession.__del__ at 0x02845810>
Traceback (most recent call last):
  File "D:\py371\lib\site-packages\aiohttp-4.0.0a1-py3.7-win32.egg\aiohttp\clien
t.py", line 269, in __del__
  File "D:\py371\lib\site-packages\aiohttp-4.0.0a1-py3.7-win32.egg\aiohttp\clien
t.py", line 894, in closed
AttributeError: _connector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\py371\lib\site-packages\coc\login.py", line 54, in login
    instance.loop.run_until_complete(instance.login(email, password))
  File "D:\py371\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "D:\py371\lib\site-packages\coc\client.py", line 191, in login
    cache_max_size=self.cache_max_size,
  File "D:\py371\lib\site-packages\coc\http.py", line 206, in __init__
    loop=self.loop, connector=connector, timeout=aiohttp.ClientTimeout(total=tim
eout)
TypeError: __init__() got an unexpected keyword argument 'loop'

I think the problem with aiohttp, I'd deleted 4.0.0a1v and installed stable 3.7.2v, but the error is still raising. What version of aiohttp should I use?

Edited: my OS is windows

**Comment by mathsman5133** [comment]
Thanks for the issue, I'll check it out

**Comment by mathsman5133** [comment]
I just pushed #0f3fb35ef15317a31a379279e4c6e7de66b4f574 and it looks like this is fixed, at least on startup. I haven't tested anything else, so please let me know if you find any other issues

**Comment by abdurahmangulamkadirov** [comment]
Thank you for your attention, I've changed it as you shown.
But there's another error:
```
SSL handshake failed on verifying the certificate
protocol: <asyncio.sslproto.SSLProtocol object at 0x02F072B0>
transport: <_SelectorSocketTransport fd=420 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "D:\py371\lib\asyncio\sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "D:\py371\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "D:\py371\lib\ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x02F072B0>
transport: <_SelectorSocketTransport closing fd=420 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "D:\py371\lib\asyncio\sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "D:\py371\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "D:\py371\lib\ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051)
```
I think, the error with aiohttp. I'll check it

**Comment by abdurahmangulamkadirov** [comment]
In client.py:
```
def __init__(
        self,
        *,
        key_count: int = 1,
        key_names: str = "Created with coc.py Client",
        key_scopes: str = "clash",
        throttle_limit: int = 10,
        loop: asyncio.AbstractEventLoop = None,
        correct_tags: bool = True,
        throttler=BasicThrottler,
        connector = None,
        timeout = 30.0,
        cache_max_size: int = 10000,
        **_,
    )
```
May be, the problem with connector?

**Comment by abdurahmangulamkadirov** [comment]
Yeah, I think I fixed SSL problem!
In your http.py module, I imported `ssl `and `certifi`, and  add a variable in constructor of your HTTPClient class:
`self.ssl_context = ssl.create_default_context(cafile=certifi.where())`
then I gave it at every request of self.__session, for example in 295 line of http.py:
`async with self.__session.request(method, url, **kwargs, **ssl = self.ssl_context**) as response`
And I did not get any SSL error

**Comment by mathsman5133** [comment]
Would you mind checking this solution out on SO? https://stackoverflow.com/a/43855394

I couldn't reproduce this when running the example folders with both Py3.7/8 and aiohttp v3.7.2

I'm happy to work out a more permanent solution so you don't have to patch the library, but I have a sneaking suspicion that that may be the issue here.
