### ISSUE TITLE
Helper/util function to cleanup tags

### ISSUE THREAD

**Issue by mathsman5133** [mathsman5133/coc.py#7]
This should take a tag (clan, player, war etc) and apply the following modifications to it:

* [ ] Capitalisation
* [ ] Changing Zero to O ('oh')
* [ ] Removing whitespace at the end/start of the string

**Comment by Jabbey92** [comment]
Does the client accept tags whether they have a preceding `#` or not? If not then maybe make it insert that as well

**Comment by mathsman5133** [comment]
Not sure. I'll test quickly

**Comment by Jabbey92** [comment]
Actually tags have zeros not O's and here's my current method to do this that I've been using:

```
def correct_tag(tag, prefix='#'):
    return prefix + re.sub(r'[\W_]+', '', tag).upper().replace('O', '0') 
```
