### ISSUE TITLE
Usage in flask

### ISSUE THREAD

**Issue by amir20** [mathsman5133/coc.py#78]
I am trying to use coc.py in a flask v2 application. Upon doing `client.login(...)` I get the following error: 

```
DEBUG:coc.http:https://developer.clashofclans.com/api/apikey/list has received {'error': 'general', 'description': 'Temporary application error, request failed.'}
```

But I see another worker that worked. My guess is that API is rejecting because workers at the same time are trying to access the API in a short amount of time. 

How do I get around this? Is there a better way to initialize client in flask? 

Is it possible to set keys manually? `client.keys` seems to be private.

**Comment by doluk** [comment]
You can use the `client.login_with_keys()` to login in with existing keys.

Without any code and more details of the error, amount of workers etc. there isn't much we can analyze in order to help you.
