### ISSUE TITLE
get_max_level_for_townhall() Not Updated for Th14

### ISSUE THREAD

**Issue by JamesTesting888** [mathsman5133/coc.py#86]
`get_max_level_for_townhall()`

Examples:
Max level for Yeti in Th14 is `3` but the max level is actually `4`
Max level for Hog Rider in th14 is `10` but the max level is actually `11`

**Comment by Westo48** [comment]
you may want to double check this, my value from this is correct

**Comment by scosco97** [comment]
This was recently fixed. #89 #84
