### ISSUE TITLE
get_current_war cwl preparation first war returning not found

### ISSUE THREAD

**Issue by Westo48** [mathsman5133/coc.py#91]
https://github.com/Westo48/coc.py/blob/db6713ec525fc75045f38991510d17cb6d22e94e/coc/client.py#L882-L883

should be able to change to

```
if cwl_round is WarRound.current_war and is_prep:
    round_tags = league_group.rounds[-1]  # for round 1 and 15min prep between rounds this is a shortcut.
```

This should return the first set of round tags when the cwl is in prep, uses `league_groups.rounds[-1]` to mirror:
https://github.com/Westo48/coc.py/blob/db6713ec525fc75045f38991510d17cb6d22e94e/coc/client.py#L894-L895

**Comment by Westo48** [comment]
https://github.com/mathsman5133/coc.py/pull/92

**Comment by txmazing** [comment]
another problem: get_current_war in cwl and 7th round also returning 6th war and not the last, the 7th war

**Comment by JamesTesting888** [comment]
txmazing, I have the same problem

**Comment by Westo48** [comment]
> another problem: get_current_war in cwl and 7th round also returning 6th war and not the last, the 7th war

When utilizing the current code or the potential fixed code? Also, is the 7th war referenced inWar?

**Comment by JamesTesting888** [comment]
> > another problem: get_current_war in cwl and 7th round also returning 6th war and not the last, the 7th war
> 
> When utilizing the current code or the potential fixed code? Also, is the 7th war referenced inWar?

No, it shows warEnded, at least for me

**Comment by Westo48** [comment]
> > > another problem: get_current_war in cwl and 7th round also returning 6th war and not the last, the 7th war
> > 
> > 
> > When utilizing the current code or the potential fixed code? Also, is the 7th war referenced inWar?
> 
> No, it shows warEnded, at least for me

haven't tested it quite yet, but I am pretty sure it is due to this line 

https://github.com/Westo48/coc.py/blob/db6713ec525fc75045f38991510d17cb6d22e94e/coc/client.py#L892

From a cursory glance I assume if it looks for the current war it looks at the second to last war in the list. If the current war is the last war it still looks for the second to last war.

**Comment by txmazing** [comment]
Should fix the 7th war problem:
https://github.com/mathsman5133/coc.py/pull/95/commits/c38bd38314930b711aef67ba1eba952a97fcdf0f

**Comment by Westo48** [comment]
> Should fix the 7th war problem:
> 
> https://github.com/mathsman5133/coc.py/pull/95/commits/c38bd38314930b711aef67ba1eba952a97fcdf0f

On the second to last war day there are still 7 rounds since the last prep round is included in the round count

**Comment by txmazing** [comment]
> > Should fix the 7th war problem:
> > [c38bd38](https://github.com/mathsman5133/coc.py/commit/c38bd38314930b711aef67ba1eba952a97fcdf0f)
> 
> On the second to last war day there are still 7 rounds since the last prep round is included in the round count

Youre right. I didnt thought about that. This could work:
https://github.com/mathsman5133/coc.py/pull/95/commits/a35a6154abbed8536a2b03eace20e48f756154b6

**Comment by Westo48** [comment]
> > > Should fix the 7th war problem:
> 
> > > [c38bd38](https://github.com/mathsman5133/coc.py/commit/c38bd38314930b711aef67ba1eba952a97fcdf0f)
> 
> > 
> 
> > On the second to last war day there are still 7 rounds since the last prep round is included in the round count
> 
> 
> 
> Youre right. I didnt thought about that. This could work:
> 
> https://github.com/mathsman5133/coc.py/pull/95/commits/a35a6154abbed8536a2b03eace20e48f756154b6

I doubt I'd be able to test it tonight (prior commitments). 

However, I have been thinking about trying to use how I used to find the current league war.

To put it very basically if there's only 1 round return the first round (CWL prep). Other than that: reverse the round list, then for each round check the state, if prep, then get the next war. This simplifies the process and always gets the correct war.

I can code it tomorrow, but it'll be another month till it can be tested (the joys of testing CWL stuff hahaha).

**Comment by Westo48** [comment]
Closing due to incorrect argument specification when used in production
