### ISSUE TITLE
WarEvents are not working for anything other than war_attack

### ISSUE THREAD

**Issue by CinematicGenius007** [mathsman5133/coc.py#98]
In documentation it is mentioned that you can use it for state (war) as well but it's just not working. Is it not implemented in the code?

**Comment by CinematicGenius007** [comment]
![Screenshot (733)](https://user-images.githubusercontent.com/75163638/149734540-26d47301-18bf-41f1-84dc-430a61653201.png)

**Comment by Anubhav1603** [comment]
> In documentation it is mentioned that you can use it for state (war) as well but it's just not working. Is it not implemented in the code?

Can you share your script what you tried🙂 this way we can figure out what's getting wrong

**Comment by CinematicGenius007** [comment]
Inside in the __init__ function of COG class
`self.bot.coc.add_events(self.on_war_state_change)`

and the function
`@coc.WarEvents.state()`
`async def on_war_state_change(self, prev_war, new_war: coc.ClanWar):`
`    print(new_war.state)`

The function was just for checking it, but it wasn't working.
And I checked manually the clans on coc where the state changed.

**Comment by CinematicGenius007** [comment]
> Inside in the **init** function of COG class `self.bot.coc.add_events(self.on_war_state_change)`
> 
> and the function `@coc.WarEvents.state()` `async def on_war_state_change(self, prev_war, new_war: coc.ClanWar):` ` print(new_war.state)`
> 
> The function was just for checking it, but it wasn't working. And I checked manually the clans on coc where the state changed.

Sorry I cannot give any more code.

Even you could give an example of using war events other than war_attack that would be splended.

**Comment by Anubhav1603** [comment]
> Sorry I cannot give any more code.

without proper code i cannot help you mate, because i dont know where are you messing things.

> Even you could give an example of using war events other than war_attack that would be splended.

all the examples in example folder are tested by me and its used by many others 😃 .

**Comment by doluk** [comment]
Closed as no response and not reproducible
