### ISSUE TITLE
Is it possible to search for opponent to attack using this API?

### ISSUE THREAD

**Issue by rajendrasp** [mathsman5133/coc.py#99]
I want to find a match in multiplayer. Is it possible?

**Comment by Kuchenmampfer** [comment]
Nope. This API only provides live data from the game, but you can not interact with it.

**Comment by rajendrasp** [comment]
Damn!! Really looking for something that can interact with the game!

**Comment by Kuchenmampfer** [comment]
I fear your only legal choice for this is the game itself
